import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,ChefHat,Boxes,ShoppingCart,BarChart3,LogOut,Plus,Trash2,Edit3,RefreshCw,Menu,X,Calculator,Save}from'lucide-react';
import{api}from'./api';
import'./styles.css';

const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const units=['g','kg','ml','l','piece','packet','other'];
const categories=[['vegetable','Vegetables'],['kitchen','Kitchen'],['dairy','Dairy Products']];

function Login({onLogin}){const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[err,setErr]=useState('');
async function submit(e){e.preventDefault();setErr('');try{const d=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('fc_token',d.token);onLogin(d.user)}catch(x){setErr(x.message)}}
return <div className="auth"><div className="auth-card"><div className="brand"><span>🍴</span><div><b>Food Cart</b><small>Cost & Profit Manager</small></div></div><h1>{mode==='login'?'Welcome back':'Create account'}</h1><p className="muted">Personal food cart calculation dashboard</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required minLength="6"/>{err&&<div className="error">{err}</div>}<button className="primary full">{mode==='login'?'Login':'Register'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create account':'Already have an account? Login'}</button></div></div>}

function Modal({title,onClose,children,wide=false}){return <div className="modal-back"><div className={`modal ${wide?'modal-wide':''}`}><div className="modal-head"><h3>{title}</h3><button className="icon" onClick={onClose}><X/></button></div>{children}</div></div>}
function PageTitle({title,subtitle,action}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Loading(){return <div className="loading">Loading…</div>}

function ProfitChart({daily,title='Profit / Loss'}){
 const max=Math.max(1,...daily.map(x=>Math.abs(Number(x.profit||0))));
 return <div className="chart-panel"><div className="chart-head"><h3>{title}</h3><span className="muted">Green = profit · Red = loss</span></div>
 <div className="bar-chart">{daily.map(x=>{const v=Number(x.profit||0);const h=Math.max(4,Math.round(Math.abs(v)/max*150));return <div className="bar-item" key={x.date} title={`${x.date}: ${money(v)}`}><div className="bar-value">{money(v)}</div><div className={`bar ${v<0?'loss':''}`} style={{height:h}}></div><small>{x.date.slice(5)}</small></div>})}</div></div>
}
function DishProfitChart({rows}){
 const list=rows.slice(0,8);const max=Math.max(1,...list.map(x=>Math.abs(Number(x.profit||0))));
 return <div className="chart-panel"><div className="chart-head"><h3>Dish-wise Profit</h3><span className="muted">Top dishes by profit</span></div><div className="dish-bars">{list.map(x=>{const v=Number(x.profit||0);return <div className="dish-bar-row" key={x.dish}><div className="dish-bar-label">{x.dish}</div><div className="dish-bar-track"><div className={`dish-bar ${v<0?'loss':''}`} style={{width:`${Math.max(3,Math.abs(v)/max*100)}%`}}></div></div><b className={v<0?'bad':'good'}>{money(v)}</b></div>})}{!list.length&&<div className="empty">No sales data for this period.</div>}</div></div>
}

function Dashboard({reload}){
 const[type,setType]=useState('today'),[d,setD]=useState(null),[from,setFrom]=useState(localToday()),[to,setTo]=useState(localToday());
 async function load(){const q=type==='custom'?`/dashboard?type=custom&from=${from}&to=${to}`:`/dashboard?type=${type}`;setD(await api(q))}
 useEffect(()=>{load()},[type,reload]);
 if(!d)return <Loading/>;
 const s=d.today;
 return <><PageTitle title="Dashboard" subtitle="Your food cart at a glance"/>
 <div className="period-tabs">{[['today','Today'],['week','This Week'],['month','This Month'],['custom','Custom']].map(x=><button className={type===x[0]?'active':''} onClick={()=>setType(x[0])} key={x[0]}>{x[1]}</button>)}{type==='custom'&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="primary small" onClick={load}>Apply</button></>}</div>
 <div className="cards"><div className="stat"><span>Sales</span><strong>{money(s.sales)}</strong><small>Net sold sales · Selected period</small></div><div className="stat"><span>Return Loss</span><strong>{money(s.returnLoss)}</strong><small>Returned plates × cost of pieces used</small></div><div className="stat"><span>Making Cost</span><strong>{money(s.makingCost)}</strong><small>Cost of plates sold</small></div><div className="stat"><span>Net Profit / Loss</span><strong className={s.profit<0?'bad':''}>{money(s.profit)}</strong><small>Net sales − making cost</small></div><div className="stat"><span>Total Plates Sell</span><strong>{s.platesMade}</strong><small>Plates entered as sold</small></div></div>
 <div className="dashboard-grid"><ProfitChart daily={d.daily} title={type==='today'?'Today Profit / Loss':type==='week'?'Weekly Profit / Loss':type==='month'?'Monthly Profit / Loss':'Custom Profit / Loss'}/><DishProfitChart rows={d.byDish}/></div>
 <div className="quick"><div><h3>Current data</h3><p className="muted">All calculations use the latest ingredient rates. Old sales keep their saved cost snapshot.</p></div><div className="pill-row"><span>🍽 {d.totals.dishes} dishes</span><span>📦 {d.totals.ingredients} ingredients</span><span>⚡ Automatic costing</span></div></div></>
}

function Ingredients({reload,setReload}){
 const[items,setItems]=useState([]),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[saving,setSaving]=useState({});
 async function load(){setItems(await api('/ingredients'))}
 useEffect(()=>{load()},[reload]);
 const filtered=useMemo(()=>items.filter(x=>(category==='all'||x.category===category)&&x.name.toLowerCase().includes(search.toLowerCase())),[items,category,search]);
 const grouped=category==='all'?categories:categories.filter(x=>x[0]===category);
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget);const body={name:f.get('name'),category:f.get('category'),currentRate:+f.get('currentRate')};try{await api(edit?`/ingredients/${edit._id}`:'/ingredients',{method:edit?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);setEdit(null);setReload(x=>x+1)}catch(x){alert(x.message)}}
 async function saveRate(i){setSaving(s=>({...s,[i._id]:true}));try{await api(`/ingredients/${i._id}`,{method:'PUT',body:JSON.stringify({currentRate:Number(i.currentRate)})});setReload(x=>x+1)}catch(x){alert(x.message)}finally{setSaving(s=>({...s,[i._id]:false}))}}
 async function del(id){if(!confirm('Delete this ingredient permanently? Related recipe lines, rate history and purchase records will also be removed.'))return;try{await api(`/ingredients/${id}`,{method:'DELETE'});setReload(x=>x+1)}catch(x){alert(x.message)}}
 return <><PageTitle title="Ingredients" subtitle="Add ingredients once, then update their ₹/kg rate from one place" action={<button className="primary" onClick={()=>setOpen(true)}><Plus/> Add Ingredient</button>}/>
 <div className="ingredient-index"><div className="index-head"><div><h3>Ingredient Index</h3><p className="muted">Daily price changes can be saved directly in this table.</p></div><div className="toolbar"><input placeholder="Search ingredient…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="ghost" onClick={load}><RefreshCw/></button></div></div>
 <div className="category-tabs"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{categories.map(x=><button key={x[0]} className={category===x[0]?'active':''} onClick={()=>setCategory(x[0])}>{x[1]}</button>)}</div>
 {grouped.map(([key,label])=>{const rows=filtered.filter(i=>i.category===key);return <div className="category-block" key={key}><div className="category-title"><h3>{label}</h3><span>{rows.length} items</span></div><div className="table-wrap"><table><thead><tr><th>Ingredient</th><th>Category</th><th>Price / kg</th><th>Last updated</th><th>Actions</th></tr></thead><tbody>{rows.map(i=><tr key={i._id}><td><b>{i.name}</b></td><td>{label}</td><td><input className="inline-rate" type="number" min="0" step="0.01" value={i.currentRate} onChange={e=>setItems(items.map(x=>x._id===i._id?{...x,currentRate:e.target.value}:x))}/></td><td>{i.updatedAt?new Date(i.updatedAt).toLocaleDateString('en-IN'): '—'}</td><td className="actions"><button className="save-icon" title="Save current price" onClick={()=>saveRate(i)} disabled={saving[i._id]}><Save/></button><button title="Edit name/category" onClick={()=>{setEdit(i);setOpen(true)}}><Edit3/></button><button className="danger" title="Delete permanently" onClick={()=>del(i._id)}><Trash2/></button></td></tr>)}{!rows.length&&<tr><td colSpan="5" className="empty">No ingredients in this category.</td></tr>}</tbody></table></div></div>})}</div>
 {open&&<Modal title={edit?'Edit Ingredient':'Add Ingredient'} onClose={()=>{setOpen(false);setEdit(null)}}><form onSubmit={save} className="form-grid"><label>Ingredient name<input name="name" defaultValue={edit?.name||''} required/></label><label>Category<select name="category" defaultValue={edit?.category||'vegetable'}>{categories.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="wide">Price per kg (₹)<input type="number" name="currentRate" min="0" step="0.01" defaultValue={edit?.currentRate??0} required/></label><div className="form-note wide">Only these details are required for an ingredient. Recipe quantities can be entered in g/kg; the rate is always maintained as ₹/kg.</div><div className="form-actions"><button type="button" className="ghost" onClick={()=>{setOpen(false);setEdit(null)}}>Cancel</button><button className="primary"><Save/> Save Ingredient</button></div></form></Modal>}</>
}

function Dishes({reload,setReload}){
 const[ds,setDs]=useState([]),[ings,setIngs]=useState([]),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[cost,setCost]=useState(null);
 async function load(){try{const[a,b]=await Promise.all([api('/dishes'),api('/ingredients')]);setDs(a);setIngs(b)}catch(e){alert(e.message)}}
 useEffect(()=>{load()},[reload]);
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget),lines=JSON.parse(f.get('lines')||'[]'),add=JSON.parse(f.get('additionalCosts')||'[]');const body={name:f.get('name'),yieldQty:+f.get('yieldQty')||0,yieldUnit:f.get('yieldUnit')||'piece',sellingPrice:+f.get('sellingPrice')||0,shareProfit:+f.get('shareProfit')||0,piecesPerDish:+f.get('piecesPerDish')||0,ingredients:lines.filter(x=>x.ingredientId&&+x.quantity>0),additionalCosts:add.filter(x=>x.name&&+x.amount>=0).map(x=>({...x,amount:+x.amount}))};if(!(body.yieldQty>0)||!(body.piecesPerDish>0))return alert('Enter total pieces made and pieces used per dish greater than zero');try{await api(edit?`/dishes/${edit._id}`:'/dishes',{method:edit?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);setEdit(null);setCost(null);setReload(x=>x+1)}catch(x){alert(x.message)}}
 async function del(id){if(!confirm('Delete this dish permanently? Its old sales reports will remain as saved snapshots.'))return;try{await api(`/dishes/${id}`,{method:'DELETE'});setReload(x=>x+1)}catch(x){alert(x.message)}}
 return <><PageTitle title="Dishes & Recipes" subtitle="Build recipes, set a fixed selling price and calculate dish profit or loss" action={<button className="primary" onClick={()=>{setEdit(null);setOpen(true)}}><Plus/> Add Dish</button>}/>
 <div className="dish-grid">{ds.map(d=><div className="dish-card" key={d._id}><div className="dish-icon">🍽️</div><div><h3>{d.name}</h3><p>{d.ingredients.length} ingredients · {d.yieldQty} {d.yieldUnit} made · {d.piecesPerDish} {d.yieldUnit} used/dish</p></div><div className="dish-price"><span>Selling price</span><b>{money(d.sellingPrice)}</b></div><div className="dish-bottom"><button className="outline" onClick={async()=>{try{setCost(await api(`/dishes/${d._id}/cost`))}catch(e){alert(e.message)}}}><Calculator/> Cost & Profit</button><button className="outline" onClick={()=>{setEdit(d);setOpen(true)}}><Edit3/></button><button className="outline danger" title="Delete dish" onClick={()=>del(d._id)}><Trash2/></button></div></div>)}{!ds.length&&<div className="empty panel">No dishes yet. Add your first recipe.</div>}</div>
 {cost&&<Modal title="Dish Cost & Profit" onClose={()=>setCost(null)}><div className="cost-lines">{cost.lines.map((x,i)=><div key={i}><span>{x.name} — {x.quantity} {x.unit}</span><b>{money(x.cost)}</b></div>)}<div><span>Additional costs</span><b>{money(cost.additionalCost)}</b></div><hr/><div><span>Total ingredient cost</span><b>{money(cost.ingredientCost)}</b></div><div><span>Total batch cost</span><b>{money(cost.totalCost)}</b></div><div><span>Total pieces made</span><b>{cost.totalPieces} {cost.totalPieces===1?'piece':'pieces'}</b></div><div><span>Cost per piece</span><b>{money(cost.costPerPiece)}</b></div><div><span>Pieces used per dish</span><b>{cost.piecesPerDish}</b></div><div><span>Cost of pieces used</span><b>{money(cost.dishCost)}</b></div><div><span>Selling price</span><b>{money(cost.sellingPrice)}</b></div><div><span>Share Profit</span><b>{money(cost.shareProfit)}</b></div><div className={`highlight ${cost.profitLoss<0?'loss-highlight':''}`}><span>{cost.profitLoss>=0?'Profit':'Loss'}</span><b>{money(Math.abs(cost.profitLoss))}</b></div><p className="muted cost-note">Profit/Loss = Selling price − cost of the pieces used − Share Profit.</p></div></Modal>}
 {open&&<DishModal edit={edit} ings={ings} onClose={()=>{setOpen(false);setEdit(null)}} onSave={save}/>}</>
}

function DishModal({edit,ings,onClose,onSave}){
 const[lines,setLines]=useState(edit?.ingredients?.map(x=>({ingredientId:x.ingredientId?._id||x.ingredientId,quantity:x.quantity,unit:x.unit}))||[ings[0]?{ingredientId:ings[0]._id,quantity:0,unit:'g'}:{ingredientId:'',quantity:0,unit:'g'}]);
 const[adds,setAdds]=useState(edit?.additionalCosts||[]);
 return <Modal title={edit?'Edit Dish':'Add Dish'} onClose={onClose} wide><form onSubmit={onSave}><div className="form-grid"><label>Dish name<input name="name" defaultValue={edit?.name||''} required/></label><label>Selling price (₹)<input type="number" step="0.01" min="0" name="sellingPrice" defaultValue={edit?.sellingPrice??0} required/></label><label>Share Profit (₹)<input type="number" step="0.01" min="0" name="shareProfit" defaultValue={edit?.shareProfit??0} required/></label><label>Total pieces made<input type="number" step="0.001" min="0.001" name="yieldQty" defaultValue={edit?.yieldQty||1} required/></label><label>Pieces used per dish<input type="number" step="0.001" min="0.001" name="piecesPerDish" defaultValue={edit?.piecesPerDish||1} required/></label><input type="hidden" name="yieldUnit" value="piece"/></div><div className="form-note form-note-space">Enter the total pieces produced from the ingredients in one batch, then enter how many pieces are used for one dish. The software calculates the cost of those pieces and compares it with the fixed selling price.</div><div className="section-head"><h4>Ingredients</h4><button type="button" className="ghost small" onClick={()=>setLines([...lines,{ingredientId:ings[0]?._id||'',quantity:0,unit:'g'}])}><Plus/> Add</button></div>{lines.map((l,i)=><div className="line-row" key={i}><select value={l.ingredientId} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,ingredientId:e.target.value}:x))}>{ings.map(x=><option key={x._id} value={x._id}>{x.name}</option>)}</select><input type="number" min="0" step="0.001" placeholder="Qty" value={l.quantity} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,quantity:e.target.value}:x))}/><select value={l.unit} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,unit:e.target.value}:x))}>{units.map(u=><option key={u}>{u}</option>)}</select><button type="button" className="danger icon" onClick={()=>setLines(lines.filter((_,j)=>j!==i))}><Trash2/></button></div>)}<div className="section-head"><h4>Additional costs</h4><button type="button" className="ghost small" onClick={()=>setAdds([...adds,{name:'',amount:0}])}><Plus/> Add</button></div>{adds.map((a,i)=><div className="line-row" key={i}><input placeholder="Oil / Gas / Packaging" value={a.name} onChange={e=>setAdds(adds.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="0" step="0.01" placeholder="₹" value={a.amount} onChange={e=>setAdds(adds.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/><span></span><button type="button" className="danger icon" onClick={()=>setAdds(adds.filter((_,j)=>j!==i))}><Trash2/></button></div>)}<input type="hidden" name="lines" value={JSON.stringify(lines)}/><input type="hidden" name="additionalCosts" value={JSON.stringify(adds)}/><div className="form-actions"><button type="button" className="ghost" onClick={onClose}>Cancel</button><button className="primary"><Save/> Save Dish</button></div></form></Modal>
}

function Sales({reload,setReload}){
 const[ds,setDs]=useState([]),[rows,setRows]=useState([]),[date,setDate]=useState(localToday()),[saving,setSaving]=useState(false);
 async function load(){try{const[d,s]=await Promise.all([api('/dishes'),api(`/sales?date=${date}`)]);setDs(d);setRows(d.map(x=>{const old=s.find(y=>y.dishId?._id===x._id);const made=Number(old?.quantity||0),returned=Number(old?.returnedQuantity||0);return{_id:old ? old._id : '',dishId:x._id,dishName:x.name,sellingPrice:Number(x.sellingPrice||0),platesSold:old?Math.max(0,made-returned):0,returnedQuantity:returned}}))}catch(e){alert(e.message)}}
 useEffect(()=>{load()},[date,reload]);
 const update=(id,key,val)=>setRows(rows.map(r=>r.dishId===id?{...r,[key]:val}:r));
 async function saveAll(){const payload={date,rows:rows.filter(r=>Number(r.platesSold)>0||Number(r.returnedQuantity)>0).map(r=>({...r,platesSold:Number(r.platesSold)||0,returnedQuantity:Number(r.returnedQuantity)||0}))};for(const r of payload.rows){if(r.platesSold<0||r.returnedQuantity<0)return alert(`Plate values cannot be negative for ${r.dishName}`)}if(!payload.rows.length)return alert('Enter at least one sale');setSaving(true);try{await api('/sales/bulk',{method:'POST',body:JSON.stringify(payload)});await load();alert('Daily sales saved successfully');setReload(x=>x+1)}catch(e){alert(e.message)}finally{setSaving(false)}}
 async function del(id){if(!confirm('Delete this daily sale entry permanently?'))return;try{await api(`/sales/${id}`,{method:'DELETE'});await load();setReload(x=>x+1)}catch(e){alert(e.message)}}
 return <><PageTitle title="Daily Sales" subtitle="Select a date, enter plates sold and plates returned, then save together"/>
 <div className="panel form-panel"><div className="sales-head"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="sales-note">Selling price is fixed in Dishes & Recipes. Daily Sales only records plates sold and plates returned.</div></div><div className="table-wrap"><table className="sales-table"><thead><tr><th>Dish</th><th>Plates Sell</th><th>Plates Returns</th><th>Net Sold</th></tr></thead><tbody>{rows.map(r=><tr key={r.dishId}><td><b>{r.dishName}</b></td><td><input type="number" min="0" step="1" value={r.platesSold} onChange={e=>update(r.dishId,'platesSold',e.target.value)}/></td><td><input type="number" min="0" step="1" value={r.returnedQuantity} onChange={e=>update(r.dishId,'returnedQuantity',e.target.value)}/></td><td><b>{Math.max(0,Number(r.platesSold||0)-Number(r.returnedQuantity||0))}</b></td></tr>)}{!rows.length&&<tr><td colSpan="4" className="empty">No dishes available. Create a dish first.</td></tr>}</tbody></table></div><div className="form-actions sales-save"><button className="primary" onClick={saveAll} disabled={saving}><Save/> {saving?'Saving…':'Save All Sales'}</button></div></div>
 <div className="panel"><h3>Saved Daily Sales</h3><p className="muted">Edit or delete any saved entry for the selected date.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Dish</th><th>Plates Sell</th><th>Plates Returns</th><th>Net Sold</th><th>Actions</th></tr></thead><tbody>{rows.filter(x=>x._id).map(r=><tr key={r._id}><td>{date}</td><td>{r.dishName}</td><td>{r.platesSold}</td><td>{r.returnedQuantity}</td><td>{Math.max(0,Number(r.platesSold||0)-Number(r.returnedQuantity||0))}</td><td className="actions"><button title="Edit" onClick={()=>document.querySelector('.sales-table')?.scrollIntoView({behavior:'smooth',block:'center'})}><Edit3/></button><button className="danger" title="Delete" onClick={()=>del(r._id)}><Trash2/></button></td></tr>)}{!rows.some(x=>x._id)&&<tr><td colSpan="6" className="empty">No saved sales for this date.</td></tr>}</tbody></table></div></div></>
}

function Reports(){
 const[type,setType]=useState('today'),[r,setR]=useState(null),[from,setFrom]=useState(localToday()),[to,setTo]=useState(localToday()),[error,setError]=useState('');
 async function load(){setError('');try{const q=type==='custom'?`/reports?type=custom&from=${from}&to=${to}`:`/reports?type=${type}`;setR(await api(q))}catch(e){setError(e.message||'Unable to load report')}}
 useEffect(()=>{load()},[type]);
 const downloadReport=()=>{const oldTitle=document.title;document.title=`Food Cart Report - ${type}`;window.print();setTimeout(()=>{document.title=oldTitle},1000)};
 if(error)return <><PageTitle title="Reports" subtitle="Daily, weekly, monthly and custom profitability"/><div className="error">{error}</div><button className="primary" onClick={load}>Retry</button></>;
 if(!r)return <Loading/>;
 return <><PageTitle title="Reports" subtitle="Daily, weekly, monthly and custom profitability" action={<button className="primary print-hide" onClick={downloadReport}>Download Report</button>}/><div className="report-tabs">{[['today','Today'],['week','This Week'],['month','This Month'],['custom','Custom']].map(x=><button className={type===x[0]?'active':''} onClick={()=>setType(x[0])} key={x[0]}>{x[1]}</button>)}{type==='custom'&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button className="primary small" onClick={load}>Apply</button></>}</div><div className="cards"><div className="stat"><span>Sales</span><strong>{money(r.summary.revenue)}</strong><small>Net sold plates × selling price</small></div><div className="stat"><span>Return Loss</span><strong>{money(r.summary.returnLoss)}</strong><small>Returned plates × cost of pieces used</small></div><div className="stat"><span>Making Cost</span><strong>{money(r.summary.makingCost)}</strong><small>Cost of plates sold</small></div><div className="stat"><span>Net Profit / Loss</span><strong className={r.summary.profit<0?'bad':''}>{money(r.summary.profit)}</strong><small>Net sales − making cost</small></div><div className="stat"><span>Total Plates Sell</span><strong>{r.summary.platesMade}</strong><small>Plates entered as sold</small></div></div><div className="dashboard-grid"><ProfitChart daily={r.daily}/><DishProfitChart rows={r.byDish}/></div><div className="panel"><h3>Dish-wise performance</h3><div className="table-wrap compact"><table><thead><tr><th>Dish</th><th>Plates Sell</th><th>Plates Returns</th><th>Net Sold</th><th>Sales</th><th>Making Cost</th><th>Profit / Loss</th><th>Per Plate Profit / Loss</th></tr></thead><tbody>{r.byDish.map(x=><tr key={x.dish}><td><b>{x.dish}</b></td><td>{x.platesSell}</td><td>{x.returned}</td><td>{x.netSold}</td><td>{money(x.sales)}</td><td>{money(x.cost)}</td><td className={x.profit>=0?'good':'bad'}>{x.profit>=0?money(x.profit):`-₹${Math.abs(Number(x.profit||0)).toLocaleString('en-IN',{maximumFractionDigits:2})}`}</td><td className={x.perPlateProfitLoss>=0?'good':'bad'}>{x.perPlateProfitLoss>=0?money(x.perPlateProfitLoss):`-₹${Math.abs(Number(x.perPlateProfitLoss||0)).toLocaleString('en-IN',{maximumFractionDigits:2})}`}</td></tr>)}{!r.byDish.length&&<tr><td colSpan="8" className="empty">No sales data in this period.</td></tr>}</tbody></table></div></div></>
}

function App(){
 const[user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[reload,setReload]=useState(0),[mobile,setMobile]=useState(false);
 useEffect(()=>{if(localStorage.getItem('fc_token'))api('/auth/me').then(x=>setUser(x.user)).catch(()=>localStorage.removeItem('fc_token'))},[]);
 if(!user)return <Login onLogin={setUser}/>;
 const nav=[['dashboard','Dashboard',LayoutDashboard],['ingredients','Ingredients',Boxes],['dishes','Dishes & Recipes',ChefHat],['sales','Daily Sales',ShoppingCart],['reports','Reports',BarChart3]];
 function content(){if(page==='dashboard')return <Dashboard reload={reload}/>;if(page==='ingredients')return <Ingredients reload={reload} setReload={setReload}/>;if(page==='dishes')return <Dishes reload={reload} setReload={setReload}/>;if(page==='sales')return <Sales reload={reload} setReload={setReload}/>;return <Reports/>}
 return <div className="app"><aside className={mobile?'open':''}><div className="brand side"><span>🍴</span><div><b>Food Cart</b><small>Manager</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'selected':''} onClick={()=>{setPage(id);setMobile(false)}}><Icon/>{label}</button>)}</nav><div className="side-bottom"><div className="user-mini">{user.name?.[0]?.toUpperCase()}<span>{user.name}<small>{user.email}</small></span></div><button onClick={()=>{localStorage.removeItem('fc_token');setUser(null)}}><LogOut/> Logout</button></div></aside><main><header><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><b>Food Cart Cost & Profit</b><span>Personal management dashboard</span></div><button className="icon" onClick={()=>setReload(x=>x+1)} title="Refresh"><RefreshCw/></button></header><div className="content">{content()}</div></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
